### PR TITLE
chore: Update kubeconfig-generator

### PR DESCRIPTION
**Pull request by Nuckal777**

### CODE REVIEW

**Comment by IvoGoman** [comment]
@ibakshay this plugin does not have a publicly available Docker Image. Could we skip the integration test for it?

**Review by IvoGoman — APPROVED** [review]

**Comment by ibakshay** [comment]
> @ibakshay this plugin does not have a publicly available Docker Image. Could we skip the integration test for it?

yes, we can skip the integration test for this plugin.

**Comment by IvoGoman** [comment]
@

> > @ibakshay this plugin does not have a publicly available Docker Image. Could we skip the integration test for it?
> 
> yes, we can skip the integration test for this plugin.

@ibakshay can you configure this?

**Comment by ibakshay** [comment]
> > > @ibakshay this plugin does not have a publicly available Docker Image. Could we skip the integration test for it?
> > 
> > 
> > yes, we can skip the integration test for this plugin.
> 
> @ibakshay can you configure this?

Yes, I will work on this issue.

**Pull request merged**
